version: '3.8'

services:
  weather-web:
    build: .
    container_name: weather-app
    ports:
      - "3000:80"

    environment:
      - OPENWEATHERMAP_API_KEY=d4f7f81129bb4e05e278163ba60b69d4
        
